version: '3'

includes:
  rethink:
    dir: rethink
    taskfile: rethink/Taskfile.yml

tasks:
  server:
    desc: Run the nats server
    cmds:
      - nats server run --clean --jetstream rethink

  clean:
    desc: Clean up the project
    cmds:
        - rm -rf ~/.local/share/nats/rethink